# Generated by Django 3.0.6 on 2020-06-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('openid', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_address',
            },
        ),
    ]
