# Generated by Django 3.0.6 on 2020-05-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('openid', models.CharField(max_length=50, unique=True)),
                ('wechat_name', models.CharField(max_length=50)),
                ('stu_id', models.CharField(max_length=9, null=True, unique=True)),
                ('credit', models.IntegerField(default=90)),
                ('auth_status', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
    ]
