# Generated by Django 3.0.6 on 2020-05-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200527_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
