# Generated by Django 3.0.6 on 2020-05-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_id', models.CharField(max_length=9, unique=True)),
                ('stu_name', models.CharField(max_length=40)),
                ('auth_status', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'tb_student',
            },
        ),
    ]
