# Generated by Django 3.0.6 on 2020-06-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200602_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='rel_credit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='taker_credit',
            field=models.IntegerField(null=True),
        ),
    ]
