# Generated by Django 3.0.6 on 2020-06-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200602_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='confirm_photo',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
