# Generated by Django 3.0.6 on 2020-06-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_ordermodel_confirm_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='confirm_photo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
